// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameNavigation = "navigation"

// Navigation mapped from table <navigation>
type Navigation struct {
	CreatedAt          *int64  `gorm:"column:created_at;type:bigint" json:"created_at"`
	CreatedBy          *string `gorm:"column:created_by;type:character varying(255)" json:"created_by"`
	ModifiedAt         *int64  `gorm:"column:modified_at;type:bigint" json:"modified_at"`
	ModifiedBy         *string `gorm:"column:modified_by;type:character varying(255)" json:"modified_by"`
	DeletedAt          *int64  `gorm:"column:deleted_at;type:bigint" json:"deleted_at"`
	DeletedBy          *string `gorm:"column:deleted_by;type:character varying(255)" json:"deleted_by"`
	NavigationID       string  `gorm:"column:navigation_id;type:character varying(255);primaryKey" json:"navigation_id"`
	NavigationName     string  `gorm:"column:navigation_name;type:character varying(255);not null" json:"navigation_name"`
	ParentNavigationID *string `gorm:"column:parent_navigation_id;type:character varying(255)" json:"parent_navigation_id"`
	SortOrder          int32   `gorm:"column:sort_order;type:integer;not null" json:"sort_order"`
	URLPath            *string `gorm:"column:url_path;type:character varying(255)" json:"url_path"`
	IsActive           *bool   `gorm:"column:is_active;type:boolean;default:true" json:"is_active"`
}

// TableName Navigation's table name
func (*Navigation) TableName() string {
	return TableNameNavigation
}
