// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRole = "roles"

// Role mapped from table <roles>
type Role struct {
	CreatedAt  *int64  `gorm:"column:created_at;type:bigint" json:"created_at"`
	CreatedBy  *string `gorm:"column:created_by;type:character varying(255)" json:"created_by"`
	ModifiedAt *int64  `gorm:"column:modified_at;type:bigint" json:"modified_at"`
	ModifiedBy *string `gorm:"column:modified_by;type:character varying(255)" json:"modified_by"`
	DeletedAt  *int64  `gorm:"column:deleted_at;type:bigint" json:"deleted_at"`
	DeletedBy  *string `gorm:"column:deleted_by;type:character varying(255)" json:"deleted_by"`
	RoleID     string  `gorm:"column:role_id;type:character varying(255);primaryKey" json:"role_id"`
	RoleName   string  `gorm:"column:role_name;type:character varying(255);not null" json:"role_name"`
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
