// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"fmt"
	"testing"

	"join/model"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
	"time"
)

func init() {
	InitializeDB()
	err := _gen_test_db.AutoMigrate(&model.Navigation{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&model.Navigation{}) fail: %s", err)
	}
}

func Test_navigationQuery(t *testing.T) {
	navigation := newNavigation(_gen_test_db)
	navigation = *navigation.As(navigation.TableName())
	_do := navigation.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(navigation.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <navigation> fail:", err)
		return
	}

	_, ok := navigation.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from navigation success")
	}
	createdAt := time.Now().Unix()

	err = _do.Create(&model.Navigation{CreatedAt: &createdAt})
	if err != nil {
		t.Error("create item in table <navigation> fail:", err)
	}

	err = _do.Save(&model.Navigation{CreatedAt: &createdAt})
	if err != nil {
		t.Error("create item in table <navigation> fail:", err)
	}

	err = _do.CreateInBatches([]*model.Navigation{
		{NavigationID: "nav1", CreatedAt: &createdAt},
		{NavigationID: "nav2", CreatedAt: &createdAt},
	}, 10)
	if err != nil {
		t.Error("create item in table <navigation> fail:", err)
	}

	_, err = _do.Select(navigation.ALL).Take()
	if err != nil {
		t.Error("Take() on table <navigation> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <navigation> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <navigation> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <navigation> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*model.Navigation{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <navigation> fail:", err)
	}

	_, err = _do.Select(navigation.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <navigation> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <navigation> fail:", err)
	}

	_, err = _do.Select(navigation.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <navigation> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <navigation> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <navigation> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <navigation> fail:", err)
	}

	_, err = _do.ScanByPage(&model.Navigation{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <navigation> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <navigation> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <navigation> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), "id")

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <navigation> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <navigation> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <navigation> fail:", err)
	}
}
