// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"fmt"
	"testing"

	"join/model"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
	"time"
)

func init() {
	InitializeDB()
	err := _gen_test_db.AutoMigrate(&model.Role{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&model.Role{}) fail: %s", err)
	}
}

func Test_roleQuery(t *testing.T) {
	role := newRole(_gen_test_db)
	role = *role.As(role.TableName())
	_do := role.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(role.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <roles> fail:", err)
		return
	}

	_, ok := role.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from role success")
	}

	createdAt := time.Now().Unix()
	err = _do.Create(&model.Role{CreatedAt: &createdAt})
	if err != nil {
		t.Error("create item in table <roles> fail:", err)
	}

	err = _do.Save(&model.Role{CreatedAt: &createdAt})
	if err != nil {
		t.Error("create item in table <roles> fail:", err)
	}

	err = _do.CreateInBatches([]*model.Role{{CreatedAt: &createdAt, RoleID: "rol1"}, {CreatedAt: &createdAt, RoleID: "rol2"}}, 10)
	if err != nil {
		t.Error("create item in table <roles> fail:", err)
	}

	_, err = _do.Select(role.ALL).Take()
	if err != nil {
		t.Error("Take() on table <roles> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <roles> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <roles> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <roles> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*model.Role{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <roles> fail:", err)
	}

	_, err = _do.Select(role.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <roles> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <roles> fail:", err)
	}

	_, err = _do.Select(role.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <roles> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <roles> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <roles> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <roles> fail:", err)
	}

	_, err = _do.ScanByPage(&model.Role{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <roles> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <roles> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <roles> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), "id")

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <roles> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <roles> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <roles> fail:", err)
	}
}
